tema : jekyll-theme-leap-day
- nombre : GitHub Action for Zeit
  usos : actions/zeit-now@1.0.0
  - nombre : Git Submodules Init
  usos : chris-short/github-action-git-submodules@v0.1.0
- nombre : la configuración de dockerize
  Estados Unidos : zcong1993/setup-dockerize@v1.1.0
  # usará 0.6.1
utiliza : dcodeIO / setup-node-nvm @ master
con :
   versión- nodo : nodo
  nodo-espejo : https://nodejs.org/download/v8-canary/
  - nombre : Acción Hugo
  usos : kevvurs/action-hugo@v1.0-rc2
  - nombre : Plantilla de acción de contenedor TypeScript
  utiliza : kevinpollet / typescript-container-action-template @ v1

on:
  # The issues event below is only needed for the default (auto) mode,
  # you can remove it otherwise
  issues:
    types: [ assigned ]
  # The issue_comment event below is only needed for the ChatOps mode,
  # you can remove it otherwise
  issue_comment:
    types: [ created ]
  pull_request:
    types: [ closed ]

jobs:
  create_issue_branch_job:
    runs-on: ubuntu-latest
    steps:
      - name: Create Issue Branch
        uses: robvanderleek/create-issue-branch@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
